### ISSUE TITLE
⚒️[FEATURE] MailChimp Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [Outerbridgeio/Outerbridge#110]
## Describe the feature you'd like
MailChimp Integration
Docs: https://mailchimp.com/developer/marketing/api/campaigns/

## ✅Tasks
- [ ] Add MailChimp action node.

## 🎯Acceptance Criteria
- [ ] MailChimp action node should have some key Marketing APIs from the docs implemented such as list, add, update, delete, send.

## 👨‍💻How to contribute
Follow this [guide](https://github.com/Outerbridgeio/Outerbridge/blob/master/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 🧱 How to create node
 - Action node [guide](https://docs.outerbridge.io/create/action-node)
 - Trigger node [guide](https://docs.outerbridge.io/create/trigger-node)
 - Webhook node [guide](https://docs.outerbridge.io/create/webhook-node)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/Y9VE4ykPDJ)👾

**Comment by utkarsh4321** [comment]
Hii @HenryHengZJ I m new in the backend but I wanted to work into it. In order to learn the backend. So if you help me with it I can work on it. Can you assign it to me?

**Comment by HenryHengZJ** [comment]
sure! reach out to us or anyone in our [Discord](https://discord.com/invite/Y9VE4ykPDJ) if you need any help

**Comment by utkarsh4321** [comment]
@HenryHengZJ Can I use atlas instead of mongo installed locally?

**Comment by utkarsh4321** [comment]
@HenryHengZJ 
<img width="480" alt="image" src="https://user-images.githubusercontent.com/30936607/197099779-61f7f526-f4ce-4680-bc1b-23f5de18c76d.png">
I m getting this error.

**Comment by HenryHengZJ** [comment]
@utkarsh4321 yes you can. Replace this `mongodb://${process.env.MONGO_HOST || 'localhost'}:27017/outerbridge` with `mongodb+srv://<user>:<password>@cluster0.qskldy2.mongodb.net/outerbridge?retryWrites=true&w=majority`. Replace those values with your user, password and clusters

**Comment by utkarsh4321** [comment]
@HenryHengZJ one more thing I need to take api key under my account and create an action node. And test everything. And then create PR. After that, you will use your Outerbridge API key to validate everything.

**Comment by utkarsh4321** [comment]
@HenryHengZJ  Where I will put my API KEY in your project so that where I want to access it I will access it. And you can also configure it easily.
