### ISSUE TITLE
⚒️[FEATURE] Helius Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [Outerbridgeio/Outerbridge#114]
## Describe the feature you'd like
Helius Integration
Docs: https://docs.helius.xyz/introduction/quick-start

## ✅Tasks
- [ ] Add Helius action node.

## 🎯Acceptance Criteria
- [ ] Helius action node should have some most of the APIs like NFT, Name, Balance implemented.

## 👨‍💻How to contribute
Follow this [guide](https://github.com/Outerbridgeio/Outerbridge/blob/master/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 🧱 How to create node
 - Action node [guide](https://docs.outerbridge.io/create/action-node)
 - Trigger node [guide](https://docs.outerbridge.io/create/trigger-node)
 - Webhook node [guide](https://docs.outerbridge.io/create/webhook-node)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/Y9VE4ykPDJ)👾

**Comment by abdullahranginwala** [comment]
This seems interesting! Can you assign this to me?

**Comment by HenryHengZJ** [comment]
definitely! reach out to me if you have any question, happy to help!

**Comment by HenryHengZJ** [comment]
#118 closing as pr merged
