### ISSUE TITLE
⚒️[FEATURE] Github Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [Outerbridgeio/Outerbridge#51]
## Describe the feature you'd like
Github integration
Docs: https://docs.github.com/en/rest

## ✅Tasks
- [x] Add Github action node.

## 🎯Acceptance Criteria
- [x] Github action node should have some key APIs from the docs implemented.

## 👨‍💻How to contribute
Follow this [guide](https://github.com/Outerbridgeio/Outerbridge/blob/master/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 🧱 How to create node
 - Action node [guide](https://docs.outerbridge.io/create/action-node)
 - Trigger node [guide](https://docs.outerbridge.io/create/trigger-node)
 - Webhook node [guide](https://docs.outerbridge.io/create/webhook-node)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/Y9VE4ykPDJ)👾

**Comment by utkarsh4321** [comment]
Hii @HenryHengZJ If anyone not working on it can I work on it? Can you assign me this issue? And can you explain to me what you want here? So that I will start working on it asap. Thankyou

**Comment by HenryHengZJ** [comment]
@utkarsh4321 appreciate the volunteer! However @chungyau97 is already working on this

**Comment by HenryHengZJ** [comment]
Closing as #120 merged
