### ISSUE TITLE
⚒️[FEATURE] Telegram Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [Outerbridgeio/Outerbridge#52]
## Describe the feature you'd like
Telegram integration. Able to send telegram message and any other key functions.
Docs: https://core.telegram.org/

## ✅Tasks
- [ ] Add Telegram action node.

## 🎯Acceptance Criteria
- [ ] Telegram action node should have some key APIs and functionalities from the docs implemented.

## 👨‍💻How to contribute
Follow this [guide](https://github.com/Outerbridgeio/Outerbridge/blob/master/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 🧱 How to create node
 - Action node [guide](https://docs.outerbridge.io/create/action-node)
 - Trigger node [guide](https://docs.outerbridge.io/create/trigger-node)
 - Webhook node [guide](https://docs.outerbridge.io/create/webhook-node)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/Y9VE4ykPDJ)👾

**Comment by tylim88** [comment]
I would like to try this

**Comment by HenryHengZJ** [comment]
@tylim88 assigned to you now! Let us know if you have any questions or need any guidance! Happy to help 🙌

**Comment by HenryHengZJ** [comment]
PR #85 merged
