### ISSUE TITLE
⚒️[FEATURE] Typeform Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [Outerbridgeio/Outerbridge#67]
## Describe the feature you'd like
Typeform Integration
Docs: https://developer.typeform.com/

## ✅Tasks
- [ ] Add Typeform action node.

## 🎯Acceptance Criteria
- [ ] Typeform action node should have some key APIs from the docs implemented such as create and response API.

## 👨‍💻How to contribute
Follow this [guide](https://github.com/Outerbridgeio/Outerbridge/blob/master/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 🧱 How to create node
 - Action node [guide](https://docs.outerbridge.io/create/action-node)
 - Trigger node [guide](https://docs.outerbridge.io/create/trigger-node)
 - Webhook node [guide](https://docs.outerbridge.io/create/webhook-node)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/Y9VE4ykPDJ)👾

**Comment by prasoonmhwr** [comment]
please assign this to me

**Comment by HenryHengZJ** [comment]
@prasoonmhwr  thanks for taking that! Let us know if you have any question in our [Discord](https://discord.com/invite/Y9VE4ykPDJ)! Note that you dont have to implement all APIs, just a few to get it going, something is always better than nothing 😊

Feel free to ⭐ the repo (it's free 😉)

**Comment by prasoonmhwr** [comment]
@HenryHengZJ can you also leave a star here ( https://github.com/prasoonmhwr/prasoonmhwr ), thanks a lot 😊

**Comment by prasoonmhwr** [comment]
@HenryHengZJ  May I know where i can find the typeform icon ?

**Comment by prasoonmhwr** [comment]
@HenryHengZJ I have created 3 APIs for this task:

1. Get all forms
2. Get responses for a given form
3. Create a new form 

Here is the video of the same.


https://user-images.githubusercontent.com/52622674/194703820-1721dd6d-0e7d-49b5-863a-e6d80f75adef.mp4

Also I am creating the PR for this same

**Comment by prasoonmhwr** [comment]
@HenryHengZJ  can we close this issue as well :)

**Comment by HenryHengZJ** [comment]
PR #99 merged 🎉
