### ISSUE TITLE
⚒️[FEATURE] Etherscan Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [Outerbridgeio/Outerbridge#73]
## Describe the feature you'd like
Etherscan Integration
Docs: https://docs.etherscan.io/

## ✅Tasks
- [ ] Add Etherscan action node.

## 🎯Acceptance Criteria
- [ ] Etherscan action node should have some key APIs from the docs implemented such as accounts, verify contracts, tokens and etc.

## 👨‍💻How to contribute
Follow this [guide](https://github.com/Outerbridgeio/Outerbridge/blob/master/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 🧱 How to create node
 - Action node [guide](https://docs.outerbridge.io/create/action-node)
 - Trigger node [guide](https://docs.outerbridge.io/create/trigger-node)
 - Webhook node [guide](https://docs.outerbridge.io/create/webhook-node)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/Y9VE4ykPDJ)👾

**Comment by issa-me-sush** [comment]
hey ! I would love  to work on this issue, could  I please be assigned?

**Comment by HenryHengZJ** [comment]
@issa-me-sush sure thing! Thanks for taking that. Assigned to you now. Feel free to reach out on [Discord](https://discord.com/invite/Y9VE4ykPDJ) if you have any question !
