### ISSUE TITLE
⚒️[FEATURE] OptimismScan Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [Outerbridgeio/Outerbridge#76]
## Describe the feature you'd like
OptimismScan Integration
Docs: https://optimistic.etherscan.io/apis

## ✅Tasks
- [ ] Add OptimismScan action node.

## 🎯Acceptance Criteria
- [ ] OptimismScan action node should have some key APIs from the docs implemented such as accounts, verify contracts, tokens and etc.

## 👨‍💻How to contribute
Follow this [guide](https://github.com/Outerbridgeio/Outerbridge/blob/master/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 🧱 How to create node
 - Action node [guide](https://docs.outerbridge.io/create/action-node)
 - Trigger node [guide](https://docs.outerbridge.io/create/trigger-node)
 - Webhook node [guide](https://docs.outerbridge.io/create/webhook-node)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/Y9VE4ykPDJ)👾

**Comment by TIGGERKUB** [comment]
Can you assign me this issue?

**Comment by tylim88** [comment]
@TIGGERKUB done 👍

**Comment by HenryHengZJ** [comment]
@TIGGERKUB glad you are taking em! Fan of your clean code 😍

**Comment by TIGGERKUB** [comment]
@HenryHengZJ I'm happy to hear that! Your project is very interesting I'm glad to be a part of it.

**Comment by HenryHengZJ** [comment]
#111 merged
