### ISSUE TITLE
⚒️[FEATURE] Solscan Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [Outerbridgeio/Outerbridge#77]
## Describe the feature you'd like
Solscan Integration
Docs: https://public-api.solscan.io/docs/#/

## ✅Tasks
- [ ] Add Solscan action node.

## 🎯Acceptance Criteria
- [ ] Solscan action node should have some key APIs from the docs implemented such as accounts, verify contracts, tokens and etc.

## 👨‍💻How to contribute
Follow this [guide](https://github.com/Outerbridgeio/Outerbridge/blob/master/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 🧱 How to create node
 - Action node [guide](https://docs.outerbridge.io/create/action-node)
 - Trigger node [guide](https://docs.outerbridge.io/create/trigger-node)
 - Webhook node [guide](https://docs.outerbridge.io/create/webhook-node)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/Y9VE4ykPDJ)👾

**Comment by TIGGERKUB** [comment]
I wanna try this. Can you assign this issue to me?

**Comment by tylim88** [comment]
assigned, if you need help, come to our [discord](https://discord.com/invite/Y9VE4ykPDJ)

**Comment by HenryHengZJ** [comment]
#106 merged
