### ISSUE TITLE
[BUG] Information icons contain HTML code. Change that to simple text

### ISSUE THREAD

**Issue by affanmustafa** [Outerbridgeio/Outerbridge#81]
**Describe the bug**
Some information icons contain HTML code with anchor element. The HTML code is serving no purpose and readable text can look better and help the user understand the purpose of the field more.

**To Reproduce**
1. Go to 'Twitter Node'
2. Click on 'Credentials' and click on '+ Add New Credential'
3. Scroll down to 'Bearer Token'
4. Hover mouse on the information icon `i`

**Expected behavior**
Plain text so that the user can better understand what the purpose of the respective text field is.

**Screenshots**

<img width="469" alt="Screenshot 2022-10-05 at 6 01 53 PM" src="https://user-images.githubusercontent.com/69677074/194066788-880f120d-41cc-4e04-b164-20624eefbc47.png">

**Setup**
 - OS: All
 - Browser: All

**Additional context**
All helper icons can be changed to show only plain text rather than HTML code.

**Comment by affanmustafa** [comment]
@HenryHengZJ Could you assign this to me? Or can I work on this without being assigned first?

**Comment by HenryHengZJ** [comment]
@affanmustafa assigned now! thanks for putting in the bug!

**Comment by HenryHengZJ** [comment]
Closing as it was fixed as part of #85
