### ISSUE TITLE
⚒️[FEATURE] Xero Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [Outerbridgeio/Outerbridge#92]
## Describe the feature you'd like
Xero Integration
Docs: https://developer.xero.com/documentation/api/accounting/invoices

## ✅Tasks
- [ ] Add Xero action node.

## 🎯Acceptance Criteria
- [ ] Xero action node should have some key Invoice APIs from the docs implemented. 

## 👨‍💻How to contribute
Follow this [guide](https://github.com/Outerbridgeio/Outerbridge/blob/master/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 🧱 How to create node
 - Action node [guide](https://docs.outerbridge.io/create/action-node)
 - Trigger node [guide](https://docs.outerbridge.io/create/trigger-node)
 - Webhook node [guide](https://docs.outerbridge.io/create/webhook-node)
 - You'll have to implement XeroOAuth2 flow, see example node - [GoogleSheet](https://github.com/Outerbridgeio/Outerbridge/tree/master/packages/components/nodes/GoogleSheet) and [tutorial](https://www.youtube.com/watch?v=VBwDwHbPaYQ&t=6s)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/Y9VE4ykPDJ)👾

**Comment by druwan** [comment]
Can I make a try on this issue?

**Comment by HenryHengZJ** [comment]
@druwan sure! This includes implementing OAuth2 flow which is not as straight-forward as having an API key, so there will be a little challenge there! Feel free to ask any question on our [Discord](https://discord.com/invite/Y9VE4ykPDJ)
